apimServiceName: ych-test
namedValues:
  - name: api-function-key
    properties:
      displayName: api-function-key
      value: "{{ ychapiv3-test-key }}"
  - name: api-instance-name
    properties:
      displayName: api-instance-name
      value: "YchApiv3-Test"
  - name: apim-base-url
    properties:
      displayName: apim-base-url
      value: "https://apiv3-test.yakimachief.com"
  - name: apim-instance-name
    properties:
      displayName: apim-instance-name
      value: "ych-test"
backends:
  - name: ychapiv3
    properties:
      description: "Ych APIv3 Functions Test Environment."
      url: "https://ychapiv3-test.azurewebsites.net/api"
      resourceId: "https://management.azure.com/subscriptions/60c5205c-b580-40d1-b796-5cecad0380e2/resourceGroups/APIV3/providers/Microsoft.Web/sites/YchApiv3-Test"
      credentials:
        header:
          "x-functions-key": [
            "{{api-function-key}}"
          ]