apimServiceName: ych-stage
namedValues:
  - name: api-description
    properties:
      displayName: api-description
      value: YchApiv3-Stage
  - name: api-function-key
    properties:
      displayName: api-function-key
      value: {{ ychapiv3-stage-key }}
  - name: api-instance-name
    properties:
      displayName: api-function-key
      value: YchApiv3-Stage
  - name: api-url
    properties:
      displayName: api-url
      value: https://ychapiv3-stage.azurewebsites.net/api
  - name: apim-base-url
    properties:
      displayName: apim-base-url
      value: https://apiv3-stage.yakimachief.com
  - name: apim-instance-name
    properties:
      displayName: apim-instance-name
      value: ych-stage
loggers:
diagnostics:
backends:
apis: