apimServiceName: ych-test
namedValues:
  - name: api-management-resource-name
    properties:
      displayName: api-management-resource-name
      value: "{#API_MANAGEMENT_SERVICE_NAME#}"
backends:
  - name: ychapiv3
    properties:
      description: "Ych APIv3 Functions Prod Environment."
      url: "https://ychapiv3.azurewebsites.net/api"
      resourceId: "https://management.azure.com/subscriptions/{#AZURE_SUBSCRIPTION_ID#}/resourceGroups/{#AZURE_RESOURCE_GROUP_NAME#}/providers/Microsoft.Web/sites/{#FUNCTION_APP_RESOURCE_NAME#}"
      credentials:
        header:
          "x-functions-key": [
            "{{ychapiv3-key}}"
          ]