apimServiceName: ych-test
namedValues:
  - name: api-management-resource-name
    properties:
      displayName: api-management-resource-name
      value: "{#AZURE_API_MANAGEMENT_RESOURCE_NAME#}"
backends:
  - name: ychapiv3
    properties:
      description: "Ych APIv3 Functions Test Environment."
      url: "https://ychapiv3-test.azurewebsites.net/api"
      resourceId: "https://management.azure.com/subscriptions/{#AZURE_SUBSCRIPTION_ID#}/resourceGroups/{#AZURE_RESOURCE_GROUP_NAME#}/providers/Microsoft.Web/sites/{#AZURE_FUNCTION_APP_RESOURCE_NAME#}"
      credentials:
        header:
          "x-functions-key": [
            "{{ychapiv3-test-key}}"
          ]